package com.system
/**
 * Generated by the Shiro plugin. This interceptor class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityInterceptor {

    //customize me
    int order = HIGHEST_PRECEDENCE+100

    ShiroSecurityInterceptor(){
        matchAll()
    }
    boolean before() {
        // Ignore direct views (e.g. the default main index page).
        //if (!controllerName) return true
        // Access control by convention.
        accessControl()
    }
    void afterView() {
    }
}
